### ISSUE TITLE
Schema file

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony-cmf/sonata-phpcr-admin-integration-bundle#26]
Just a reminder. When we have a clear configuration, we have to put it into the bundles schema file.

**Comment by wouterj** [comment]
👎 As the factories can be added dynamically, we have to allow any element and any attribute in the bundles.

**Comment by ElectricMaxxx** [comment]
Can one schema file include others? I mean the factories can link their own schema for their section. And we would dynamically include it in the main file.

**Comment by wouterj** [comment]
No, it can't. We can of course add all CMF bundles in the schema file, but this means we'll get false positives (e.g. a `<content/>` node is only available if the CmfContentBundle is registered, the XSD will act like it always exists).

I think we sadly can't do anything more here.

**Comment by ElectricMaxxx** [comment]
So we should close this one?
