### ISSUE TITLE
treebrowser issue

### ISSUE THREAD

**Issue by kermorgant** [symfony-cmf/sonata-phpcr-admin-integration-bundle#73]
Hello,

I wrote about my issue [here](https://github.com/symfony-cmf/sonata-phpcr-admin-integration-bundle/pull/52).

To sum up, the does not render completely, shows an error for a specific node which loads its content via a specific query which ends with this error message :

No resource found at path "/menu/main/services-item" for repository "default"
No PHPCR-ODM document could be found at "/menu/main/services-item"

https://snag.gy/ebP4YI.jpg
https://snag.gy/szoBnm.jpg

It could very well be due to my configuration, as it's one of my first attempts at setting up the cmf and I still don't understand well what I'm doing :)

Regards
Mikael

**Comment by ElectricMaxxx** [comment]
I think there are two issues:

- missing option to display the complete root: if it exists yet and i don't implement it, it belongs to the admin-integration. It has to be added there.
- Seems that the treebrowser actually needs the complete tree to generate the api request. It does a parent walk, and builds the Nodes's id for the api request from the (tree-) node's keys, when there is not root node (i.e /cms) the api call is false at all.

**Comment by kermorgant** [comment]
Thanks.
Got it working by putting this in the config file 

``
cmf_menu:
    persistence:
        phpcr:
            menu_basepath: /cms
            content_basepath: /cms

**Comment by ElectricMaxxx** [comment]
Indeed there are some default values for base paths in sonata-integration which get null some days ago. There is still an open PR on sandbox where you can see the changes we made. 
But @WouterJ shouldn't some of the parameters be overwritten by the parameters in the base bundles?

**Comment by ElectricMaxxx** [comment]
@kermorgant is that issue still relevant? i did several fixes on tree. Does it work now?

**Comment by kermorgant** [comment]
Hi,

Sorry, time has gone and I have forgotten the details so I'm not sure I still have the correct repo/branch to reproduce that bug.
On the other side, my project where the cmf is running does not show this issue so I see no reason not to close this.

Thanks
