### ISSUE TITLE
Align form_group/form_tab configuration

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony-cmf/sonata-phpcr-admin-integration-bundle#92]
For block, menu and core we find the configurations for `form_group` and `form_tab` under an `extensions` node. For seo it is on the base, routing has nothing.
We should align the configuration here from my POV

**Comment by dbu** [comment]
agreed. this is a blocker, we should not have 1.1 already need to deprecate an inconsistent way of configuration.

**Comment by ElectricMaxxx** [comment]
btw: why is the form_tab/group translation in the configuration for all extensions and not for general admins.? @wouterj ping

**Comment by ElectricMaxxx** [comment]
Reopend as @wouterj had some more hints after the merge.
